<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Memory Master</title>
    <link rel="stylesheet" href="style.css">
    <link
        href="https://fonts.googleapis.com/css2?family=Fredoka:wght@400;600&family=Nunito:wght@400;700&family=Orbitron:wght@500;700&display=swap"
        rel="stylesheet">
</head>

<body class="theme-landing">
    <!-- Audio Elements (Synthesis Fallback mostly, but structure here) -->

    <!-- Main Menu -->
    <div id="main-menu" class="screen active">
        <h1 class="game-title">Memory<br>Master</h1>
        <div class="menu-controls">
            <button id="btn-start" class="btn-primary">Play Game</button>
            <button id="btn-levels" class="btn-primary">Levels</button>
            <button id="btn-settings" class="btn-primary">Settings</button>
        </div>

        <div class="level-select-container hidden">
            <h2>Select Level</h2>
            <div id="level-grid" class="level-grid">
                <!-- Generated by JS -->
            </div>
            <button id="btn-back-levels" class="btn-small">Back</button>
        </div>

        <div class="settings-menu-container hidden">
            <h2>Settings</h2>
            <div class="settings-grid">
                <div class="settings-group">
                    <h3>🔊 Audio</h3>
                    <div class="setting-row">
                        <label>Music</label>
                        <label class="switch large">
                            <input type="checkbox" id="set-music" checked>
                            <span class="slider round"></span>
                        </label>
                    </div>
                    <div class="setting-row">
                        <label>Sound Effects</label>
                        <label class="switch large">
                            <input type="checkbox" id="set-sfx" checked>
                            <span class="slider round"></span>
                        </label>
                    </div>
                    <div class="setting-row column">
                        <label>Volume: <span id="vol-display">50%</span></label>
                        <input type="range" id="set-volume" min="0" max="100" value="50" class="large-slider">
                    </div>
                </div>

                <div class="settings-group">
                    <h3>🎮 Gameplay</h3>
                    <div class="setting-row">
                        <label>Flip Speed</label>
                        <select id="set-speed" class="large-select">
                            <option value="1.0s">Slow</option>
                            <option value="0.6s" selected>Normal</option>
                            <option value="0.3s">Fast</option>
                        </select>
                    </div>
                    <div class="setting-row">
                        <label>Theme</label>
                        <select id="set-theme-mode" class="large-select">
                            <option value="light" selected>Light Mode</option>
                            <option value="dark">Dark Mode</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="settings-actions">
                <button id="btn-back-settings" class="btn-primary">Back</button>
            </div>
        </div>
    </div>

    <!-- Game HUD -->
    <div id="game-hud" class="hud hidden">
        <div class="hud-top">
            <div class="level-info">
                <span id="level-display">Level 1</span>
                <span id="theme-display">Insects</span>
            </div>
            <div class="score-container">
                <div class="star-rating" id="star-display">
                    <span class="star empty">★</span><span class="star empty">★</span><span class="star empty">★</span>
                </div>
                <div class="score-value" id="score-display">0</div>
            </div>
            <div class="timer-container">
                <div id="timer-bar-bg" class="timer-bar-bg">
                    <div id="timer-bar-fill" class="timer-bar-fill"></div>
                </div>
                <span id="time-display">00:00</span>
            </div>
            <div class="hud-controls">
                <button id="btn-restart" class="btn-icon">↺</button>
                <button id="btn-pause" class="btn-icon">⏸</button>
            </div>
        </div>
    </div>

    <!-- Game Board -->
    <div id="game-screen" class="screen hidden">
        <div id="game-board" class="game-board">
            <!-- Cards generated here -->
        </div>
        <div id="preview-overlay" class="preview-overlay hidden">
            <h2>Memorize!</h2>
            <div class="countdown" id="preview-countdown">3</div>
        </div>
    </div>

    <!-- Modals -->
    <div id="modal-overlay" class="modal-overlay hidden">
        <!-- Level Complete Modal -->
        <div id="modal-level-complete" class="modal hidden">
            <h2>Level Complete!</h2>
            <div class="stars-result" id="modal-stars">★★★</div>
            <p id="modal-score">Score: 1200</p>
            <p id="modal-message">Awesome Job!</p>
            <div class="modal-buttons">
                <button id="btn-next-level" class="btn-primary">Next Level</button>
                <button id="btn-replay-level" class="btn-secondary">Replay</button>
            </div>
        </div>

        <!-- Game Over Modal -->
        <div id="modal-game-over" class="modal hidden">
            <h2>Time's Up!</h2>
            <p>Don't give up!</p>
            <div class="modal-buttons">
                <button id="btn-retry-level" class="btn-primary">Try Again</button>
                <button id="btn-quit" class="btn-secondary">Main Menu</button>
            </div>
        </div>

        <!-- Pause Modal -->
        <div id="modal-pause" class="modal hidden">
            <h2>Paused</h2>
            <div class="modal-buttons">
                <button id="btn-resume" class="btn-primary">Resume</button>
                <button id="btn-quit-pause" class="btn-secondary">Quit</button>
            </div>
            <div class="settings-toggle">
                <label>Sound: <input type="checkbox" id="chk-sound" checked></label>
                <label>Music: <input type="checkbox" id="chk-music" checked></label>
            </div>
        </div>
        <!-- Victory Modal -->
        <div id="modal-victory" class="modal hidden victory-modal">
            <h1 class="victory-title">You Are the Ultimate<br>Memory Master!</h1>
            <div class="victory-effects">✨ 🎉 ✨</div>
            <div class="modal-buttons">
                <button id="btn-victory-replay" class="btn-primary">Try Again</button>
                <button id="btn-victory-menu" class="btn-secondary">Main Menu</button>
            </div>
        </div>
    </div>

    <script src="audio_manager.js"></script> <!-- Will create this too -->
    <script src="script.js"></script>
</body>

</html>